name: Build and Deploy

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} # Your server's IP address
          username: ${{ secrets.SSH_USERNAME }} # Your server's username
          key: ${{ secrets.SSH_KEY }} # Your server's SSH private key
          script: |
            cd /var/www/maschou-fe-dev/
            git pull
            npm install
            npm rm -rf .next
            npm run build
            pm2 restart all
            pm2 ls
